services:
    push_sender_nginx:
        image: nginx:stable-alpine
        container_name: push_sender_nginx_container
        ports:
            - "8080:80"
        volumes:
            - ../app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - push_sender_php
        networks:
            - push_sender_network
    
    push_sender_php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: push_sender_php_container
        ports:
            - "9000:9000"
        volumes:
            - ../app:/var/www/project
        networks:
            - push_sender_network

networks:
    push_sender_network: